/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "marche.h"
#include <string.h>
// Les différents magasins
caddie formules;
caddie prodindv;
// Les paniers
article ppb;
article mpb;
article gpb;
// Les articles individuels
article pomme;
article thon;
article tofu;
// Les comptes, avant et après connection
compte  moncompte;
compte moncomptetest;
compte  moncompteCo;
// Les commandes
commande macommande;
commandes mesCommandes;
commandes Commandesreset;
// La livraison
livraison malivraison;
// Boolean pour empecher de trop suprimer
int sup;
// Initialisation des commandes
void mesCommandes_init(commandes * mesCommandes){
  int i;
  for(i=0;i<3;i++){
    mesCommandes->mesLivraison[i].date[0]= '\0';

  }
}
// Fonction qui fait un flush
void purger(void)
{
   char c;
   while((c=getchar()) != '\n' && c != EOF)
   {
   }
}

// Gestion de mon caddie
gestionArticle monCaddie(
){
  int i, reponse = 1;
  float total = 0;
  gestionArticle deletecaddie;
  // J'identifie qu'il faut faire une suppression
  strcpy(deletecaddie.unArticle.nom, "OUI");
  deletecaddie.moncaddie = moncompteCo.monCaddie;
  // Affichage
  for (i=0;i<3;i++){
    printf("\n");
    printf("\033[1;36m");
    printf("Produit [%d] :", i+1);
    printf("\033[0;0m");
    printf(" %s --", moncompteCo.monCaddie.mesArticles[i].nom);
    printf("\033[1;33m");
    printf(" prix : %.2f\n",moncompteCo.monCaddie.mesArticles[i].prix );
    printf("\033[0;0m");
    total += moncompteCo.monCaddie.mesArticles[i].prix;
  }
  printf("\033[1;33m");
  printf(" Total : %.2f\n\n", total );
  printf("\033[0;0m");
  while(reponse != 0){
    printf("Que voulez vous faire ? (entrez le code)\n");
    printf("[1 - 3] -> Supprimer\n");
    printf("[0] <- Retour\n");
    printf("Code : ");
    scanf("%d", &reponse);
    // Si le produit n'existe pas je l'identifie pour ne pas faire une fausse suppression
    if(strcmp(moncompteCo.monCaddie.mesArticles[reponse - 1].nom,"")  == 0){
      sup =1;
    } else{
      sup = 0;
    }
    // En fonction de l'utilisateur
    switch (reponse) {
      // Retour
      case 0:
        strcpy(deletecaddie.unArticle.nom, "NON");
        return deletecaddie;
        break;
        // suprimer l'article n°1
      case 1:
        strcpy(deletecaddie.moncaddie.mesArticles[reponse - 1].nom, "asup");
        if(strcmp(moncompteCo.monCaddie.mesArticles[reponse - 1].nom,"") !=0){
          printf("\033[1;31m");
          printf("\n");
          printf("%s supprimé du caddie !\n", moncompteCo.monCaddie.mesArticles[reponse - 1].nom);
          printf("\033[0;0m");
        }
        return deletecaddie;
        break;
        // Supprimer l'article n°2
      case 2:
        strcpy(deletecaddie.moncaddie.mesArticles[reponse - 1].nom, "asup");
        if(strcmp(moncompteCo.monCaddie.mesArticles[reponse - 1].nom,"") !=0){
          printf("\033[1;31m");
          printf("\n");
          printf("%s supprimé du caddie !\n", moncompteCo.monCaddie.mesArticles[reponse - 1].nom);
          printf("\033[0;0m");
        }
        return deletecaddie;
        break;
        // Supprimer l'article n°3
      case 3:
        strcpy(deletecaddie.moncaddie.mesArticles[reponse - 1].nom, "asup");
        if(strcmp(moncompteCo.monCaddie.mesArticles[reponse - 1].nom,"") !=0){
          printf("\033[1;31m");
          printf("\n");
          printf("%s supprimé du caddie !\n", moncompteCo.monCaddie.mesArticles[reponse - 1].nom);
          printf("\033[0;0m");
        }
        return deletecaddie;
        break;
        // Ou mauvaise instruction
      default:
        printf("\033[1;33m");
        printf("ATTENTION : Mauvais code\n");
        printf("\033[0;0m");
        break;
    }
  }
}

// Gestion des paniers tout fait
gestionArticle lesformules(){
  int i;
  gestionArticle  ajoutcaddie;
  int reponse = 1;
    // J'initialise les articles
    strcpy(ppb.nom, "Petit P");
		strcpy(ppb.description, "Petit!");
		ppb.prix = 16;
		strcpy(mpb.nom, "Moyen P");
		strcpy(mpb.description, "moyen !");
		mpb.prix = 24;
		strcpy(gpb.nom, "Grand P");
		strcpy(gpb.description, "Panier !");
    gpb.prix = 30;
    // J'initialise formules avec mes articles
    strcpy(formules.mesArticles[0].nom, ppb.nom);
    strcpy(formules.mesArticles[0].description, ppb.description);
    formules.mesArticles[0].prix = ppb.prix;

		strcpy(formules.mesArticles[1].nom, mpb.nom);
    strcpy(formules.mesArticles[1].description, mpb.description);
    formules.mesArticles[1].prix = mpb.prix;

		strcpy(formules.mesArticles[2].nom, gpb.nom);
    strcpy(formules.mesArticles[2].description, gpb.description);
    formules.mesArticles[2].prix = gpb.prix;
    // Affichage
    for(i=0;i<3;i++){
      printf("\n");
      printf("\033[1;36m");
      printf("[%d] -> %s :\n", i+1, formules.mesArticles[i].nom);
      printf("\033[0;0m");
      printf("%s \n", formules.mesArticles[i].description);
      printf("\033[1;33m");
      printf("%.2f €\n", formules.mesArticles[i].prix);
      printf("\033[0;0m");
      printf("______________________________________\n");
    }
    // En fonction de l'utilisateur
    while(reponse != 0){
      printf("Merci de selectionner le panier souhaité, code [0] pour retourner au menu\n");
      printf("Ajouter au caddie le code : ");
      while(scanf("%d", &reponse) != 1){
        printf("\033[1;31m");
        printf("Merci de rentrer un code valide !\n");
        printf("\033[0;0m");
        printf("Code : ");
      };
      switch (reponse) {
        // Quitter
        case 0:
          break;
        // Ajouter l'article 1
        case 1:
          strcpy(ajoutcaddie.unArticle.nom, formules.mesArticles[0].nom);
          strcpy(ajoutcaddie.unArticle.description, formules.mesArticles[0].description);
          ajoutcaddie.unArticle.prix = formules.mesArticles[0].prix;
          ajoutcaddie.moncaddie = moncompteCo.monCaddie;
          return ajoutcaddie;
          break;
        // Ajouter l'article 2
        case 2:
          strcpy(ajoutcaddie.unArticle.nom, formules.mesArticles[1].nom);
          strcpy(ajoutcaddie.unArticle.description, formules.mesArticles[1].description);
          ajoutcaddie.unArticle.prix = formules.mesArticles[1].prix;
          ajoutcaddie.moncaddie = moncompteCo.monCaddie;
          return ajoutcaddie;
          break;
        // Ajouter l'article 3
        case 3:
          strcpy(ajoutcaddie.unArticle.nom, formules.mesArticles[2].nom);
          strcpy(ajoutcaddie.unArticle.description, formules.mesArticles[2].description);
          ajoutcaddie.unArticle.prix = formules.mesArticles[2].prix;
          ajoutcaddie.moncaddie = moncompteCo.monCaddie;
          return ajoutcaddie;
          break;
        // Mauvais code
        default:
          printf("\033[1;33m");
          printf("ATTENTION : Mauvais code\n");
          printf("\033[0;0m");
          break;
        }
    }
  }

  // Gestion des articles individuels
  gestionArticle lesprodindv(){
    int i;
    gestionArticle  ajoutcaddie;
    int reponse = 1;
      // J'initialise les produits individuels
      strcpy(pomme.nom, "Pomme");
  		strcpy(pomme.description, "pomme !");
  		pomme.prix = 0.30;
  		strcpy(thon.nom, "Thon");
  		strcpy(thon.description, "Thon !");
  		thon.prix = 3.56;
  		strcpy(tofu.nom, "Tofu");
  		strcpy(tofu.description, "Tofu !");
      tofu.prix = 5.57;
      // Je renseigne les produits individuels
      strcpy(prodindv.mesArticles[0].nom, pomme.nom);
      strcpy(prodindv.mesArticles[0].description, pomme.description);
      prodindv.mesArticles[0].prix = pomme.prix;

  		strcpy(prodindv.mesArticles[1].nom, thon.nom);
      strcpy(prodindv.mesArticles[1].description, thon.description);
      prodindv.mesArticles[1].prix = thon.prix;

  		strcpy(prodindv.mesArticles[2].nom, tofu.nom);
      strcpy(prodindv.mesArticles[2].description, tofu.description);
      prodindv.mesArticles[2].prix = tofu.prix;
      // Affichage
      for(i=0;i<3;i++){
        printf("\n");
        printf("\033[1;36m");
        printf("[%d] -> %s :\n", i+1, prodindv.mesArticles[i].nom);
        printf("\033[0;0m");
        printf("%s \n", prodindv.mesArticles[i].description);
        printf("\033[1;33m");
        printf("%.2f €\n", prodindv.mesArticles[i].prix);
        printf("\033[0;0m");
        printf("______________________________________\n");
      }
      // En fonction de l'utilisateur
      while(reponse != 0){
        printf("Merci de selectionner le produit souhaité, code [0] pour retourner au menu\n");
        printf("Ajouter au caddie le code : ");
        purger();
        while(scanf("%d", &reponse) != 1){
          purger();
          printf("\033[1;31m");
          printf("Merci de rentrer un code valide !\n");
          printf("\033[0;0m");
          printf("Code : ");
        };
        switch (reponse) {
          case 0:
            break;
          case 1:
            strcpy(ajoutcaddie.unArticle.nom, prodindv.mesArticles[0].nom);
            strcpy(ajoutcaddie.unArticle.description, prodindv.mesArticles[0].description);
            ajoutcaddie.unArticle.prix = prodindv.mesArticles[0].prix;
            ajoutcaddie.moncaddie = moncompteCo.monCaddie;
            return ajoutcaddie;
            break;
          case 2:
            strcpy(ajoutcaddie.unArticle.nom, prodindv.mesArticles[1].nom);
            strcpy(ajoutcaddie.unArticle.description, prodindv.mesArticles[1].description);
            ajoutcaddie.unArticle.prix = prodindv.mesArticles[1].prix;
            ajoutcaddie.moncaddie = moncompteCo.monCaddie;
            return ajoutcaddie;
            break;
          case 3:
            strcpy(ajoutcaddie.unArticle.nom, prodindv.mesArticles[2].nom);
            strcpy(ajoutcaddie.unArticle.description, prodindv.mesArticles[2].description);
            ajoutcaddie.unArticle.prix = prodindv.mesArticles[2].prix;
            ajoutcaddie.moncaddie = moncompteCo.monCaddie;
            return ajoutcaddie;
            break;
          default:
            printf("\033[1;33m");
            printf("ATTENTION : Mauvais code\n");
            printf("\033[0;0m");
            break;
          }
      }
  }

// programme principal
void
marche_prog_1(char *host)
{
  //Déclatration des variables
	char c;
  caddie  *result_3;
  gestionArticle  ajoutcaddie, delecaddie;
  int reponse = 1;
	CLIENT *clnt;
	compte  *inscrit_result;
	compte  *connexion_result;
	compteConnexion  arguments_connexion;
	caddie  *result_4;
	int  *result_5;
	payement  cartebleu;
	commandes  *result_6;
	gestionCommande  gestionCommande;
  int indexarticle = 0;
  int i, j;
  float total;

#ifndef	DEBUG
	clnt = clnt_create (host, MARCHE_PROG, MARCHE_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
  // Affichage en vert
  printf("\n");
  printf("\033[1;32m");
  printf("Bienvenue sur Panier Bio !\n");
  printf("\033[0;0m");
  moncompteCo.type = 4;
// Affichage
while(reponse != 0){
    printf("\n");
  if(moncompteCo.type == 4){
    printf("Que voulez vous faire ? (entrez le code)\n");
    printf("[1] -> Inscription\n");
    printf("[2] -> Connection\n");
    printf("Code : ");
    while(scanf("%d", &reponse) != 1){
      purger();
      printf("\033[1;31m");
      printf("Merci de rentrer un code valide !\n");
      printf("\033[0;0m");
      printf("Code : ");
    };
    // La réponse de l'utilisateur
    switch (reponse) {
      // L'inscription
      case 1:
        printf("\n");
        printf("\033[1;32m");
        printf("Merci de vous inscrire sur PanierBio ! Création du compte :\n");
      	printf("Quel est type de votre compte ? \n");
        printf("\033[0;0m");
        printf("[1] -> Client\n");
        printf("[2] -> Fournisseur\n");
        printf("[3] -> Point-Relais\n");
        printf("Code : ");
        while(scanf("%d", &moncompte.type) != 1){
          purger();
          printf("\033[1;31m");
          printf("Merci de rentrer un code valide !\n");
          printf("\033[0;0m");
          printf("Code : ");
        };

      	if(moncompte.type == 1){
      		printf("Prénom : ");
      		scanf("%s", moncompte.prenom);
      	}

      	printf("Nom : ");
      	scanf("%s", moncompte.nom);
      	printf("Email : ");
      	scanf("%s", moncompte.email);
      	printf("Mot de passe : ");
      	scanf("%s", moncompte.password);
        purger();
      	printf("Adresse : ");
        unsigned i = 0;
        while ((c = getchar()) != '\n') {
          moncompte.adresse[i++] = c;
        }

      	inscrit_result = inscription_1(&moncompte, clnt);
      	if (inscrit_result == (void *) NULL) {
      		clnt_perror (clnt, "Inscription call failed");
      	}
        // Je le récupère pour tester si il n'y a pas de doublons
        moncomptetest = *inscrit_result;
        if(moncomptetest.type != -8){
          printf("\033[1;32m");
          printf("Inscription effectuée, merci de vous connecter\n");
          printf("\033[0;0m");
        } else {
          printf("\033[1;31m");
          printf("ERREUR : Cet Email existe déjà !\n");
          printf("\033[0;0m");
        }
        break;
      // La connnexion
      case 2:
        printf("\033[1;32m");
        printf("\nConnexion\n");
        printf("\033[0;0m");
        printf("Email : ");
        printf("\033[0;0m");
        scanf("%s", arguments_connexion.email);
        printf("Mot de passe : ");
        scanf("%s", arguments_connexion.password);

        connexion_result = connexion_1(&arguments_connexion, clnt);
        if (connexion_result == (compte *) NULL) {
          clnt_perror (clnt, "Connexion call failed");
        }

        strcpy(moncompteCo.adresse, connexion_result->adresse);
        strcpy(moncompteCo.nom, connexion_result->nom);
        strcpy(moncompteCo.prenom, connexion_result->prenom);
        strcpy(moncompteCo.email, connexion_result->email);
        moncompteCo.type = connexion_result->type;
        strcpy(moncompteCo.password, connexion_result->password);

        if (moncompteCo.type == 4){
          printf("\033[1;31m");
          printf("ERREUR : Mot de passe ou Email faux \n");
          printf("\033[0;0m");
        } else {
          printf("\033[1;32m");
          printf("Bonjour %s %s !\n", moncompteCo.nom, moncompteCo.prenom);
          printf("\033[0;0m");
        }
        break;
      // Quitter
      case 0:
        printf("\033[1;32m");
        printf("Merci d'avoir utilisé PanierBio, ciao !\n");
        printf("\033[0;0m");
        break;
      // Si c'est un autre code
      default:
        printf("\033[1;33m");
        printf("ATTENTION : Mauvais code\n");
        printf("\033[0;0m");
        break;
    }
  }
  // Si il est connecté
  if(moncompteCo.type != 4){
    printf("\033[1;32m");
    printf("\n");
    printf("Que puis-je faire pour vous %s %s ?\n", moncompteCo.nom, moncompteCo.prenom);
    printf("\033[0;0m");
    printf("[1] -> Voir les formules\n");
    printf("[2] -> Voir les articles individuels\n");
    printf("[3] -> Voir mon caddie\n");
    printf("[4] -> Valider mon caddie\n");
    printf("[5] -> Voir mes commandes en cours\n");
    printf("Code : ");
    while(scanf("%d", &reponse) != 1){
       purger();
       printf("\033[1;31m");
       printf("Merci de rentrer un code valide !\n");
       printf("\033[0;0m");
       printf("Code : ");
    };

    // Choix de l'utilisateur
    switch (reponse) {
      // Ajouter les paniers
      case 1:
        if (indexarticle < 3) {
          ajoutcaddie = lesformules();
          result_3 = ajoutcaddie_1(&ajoutcaddie, clnt);
          if (result_3 == (void *) NULL) {
            clnt_perror (clnt, "Erreur lors de l'ajout");
          }
          if(result_3->mesArticles[0].prix != 0.000000 ){
          strcpy(moncompteCo.monCaddie.mesArticles[indexarticle].nom,result_3->mesArticles[0].nom);
          strcpy(moncompteCo.monCaddie.mesArticles[indexarticle].description,result_3->mesArticles[0].description);
          strcpy(moncompteCo.monCaddie.mesArticles[indexarticle].description,result_3->mesArticles[0].description);
          moncompteCo.monCaddie.mesArticles[indexarticle].prix = result_3->mesArticles[0].prix;
          printf("\033[1;32m");
          printf("\n");
          printf("%s ajouté dans le caddie !\n", moncompteCo.monCaddie.mesArticles[indexarticle].nom);
          printf("\033[0;0m");
          indexarticle ++;
          }
        } else {
          printf("\033[1;31m");
          printf("ERREUR : Votre caddie est plein !");
          printf("\033[0;0m");
        }
        break;
      // Ajouter produit individuels
      case 2:
        if (indexarticle < 3) {
          ajoutcaddie = lesprodindv();
          result_3 = ajoutcaddie_1(&ajoutcaddie, clnt);
          if (result_3 == (void *) NULL) {
            clnt_perror (clnt, "Erreur lors de l'ajout");
          }
          if(result_3->mesArticles[0].prix != 0.000000 ){
          strcpy(moncompteCo.monCaddie.mesArticles[indexarticle].nom,result_3->mesArticles[0].nom);
          strcpy(moncompteCo.monCaddie.mesArticles[indexarticle].description,result_3->mesArticles[0].description);
          strcpy(moncompteCo.monCaddie.mesArticles[indexarticle].description,result_3->mesArticles[0].description);
          moncompteCo.monCaddie.mesArticles[indexarticle].prix = result_3->mesArticles[0].prix;
          printf("\033[1;32m");
          printf("\n");
          printf("%s ajouté dans le caddie !\n", moncompteCo.monCaddie.mesArticles[indexarticle].nom);
          printf("\033[0;0m");
          indexarticle ++;
          }
        } else {
          printf("\033[1;31m");
          printf("ERREUR : Votre caddie est plein !");
          printf("\033[0;0m");
        }
        break;
      // Affichage du caddie
      case 3:
        delecaddie = monCaddie();
        if (strcmp(delecaddie.unArticle.nom, "NON") != 0){
          result_4 = supprimecaddie_1(&delecaddie, clnt);
          if (result_4 == (void *) NULL) {
            clnt_perror (clnt, "suppresion call failed");
          }
          for(i=0;i<3;i++){
            strcpy(moncompteCo.monCaddie.mesArticles[i].nom, result_4->mesArticles[i].nom);
            strcpy(moncompteCo.monCaddie.mesArticles[i].description,result_4->mesArticles[i].description);
            strcpy(moncompteCo.monCaddie.mesArticles[i].description,result_4->mesArticles[i].description);
            moncompteCo.monCaddie.mesArticles[i].prix = result_4->mesArticles[i].prix;
          }
          if(sup != 1)indexarticle --;
        }
        break;
      // Renseignments bancaires
      case 4:
        printf("\033[1;32m");
        printf("\nRenseignements bancaires : \n");
        printf("\033[0;0m");
        printf("\nMerci de renseigner votre carte bancaire :\n");
        printf("Par mesure de sécurité elle ne sera pas enregistré\n\n");
        printf("Numéro : ");
        while (scanf("%d",&cartebleu.numerocarte) != 1) {
          purger();
          printf("\033[1;31m");
          printf("Merci de rentrer un numéro de carte valide !\n");
          printf("\033[0;0m");
          printf("Code : ");
        };
        printf("Titulaire : ");
        scanf("%s",cartebleu.nom);
        printf("Date d'expiration : ");
        scanf("%s",cartebleu.dateexp);
        printf("Sécurité : ");
        while(scanf("%d",&cartebleu.numerosecu) != 1){
          purger();
          printf("\033[1;31m");
          printf("Merci de rentrer un code de sécurité valide !\n");
          printf("\033[0;0m");
          printf("Code : ");
        };
        result_5 = 0;
        result_5 = payement_1(&cartebleu, clnt);
    	  if (result_5 == (int *) NULL) {
    		    clnt_perror (clnt, "call failed");
    	  }
        printf("\033[1;32m");
        printf("\nPayement Effectué !\n");
        printf("\033[0;0m");
        // Création de la commande
        macommande.monPayement = cartebleu;
        macommande.compteClient = moncompteCo;
        macommande.caddieCommande = moncompteCo.monCaddie;
        mesCommandes_init(&mesCommandes);
        malivraison.maCommande = macommande;
        printf("\033[1;32m");
        printf("Renseignments livraison : \n");
        printf("\033[0;0m");
        printf("Choisir le jour de livraison idéal :\n");
        scanf("%s", malivraison.date);
        printf("Choisir l'heure de livraison idéal :\n");
        scanf("%s", malivraison.horaire);
        printf("Merci la commande est en attente de confirmation\n");
        printf("Une proposition de date et d'heure vous sera proposé en prenant en compte vos demandes\n");
        for(i =0;i<3;i++){
          strcpy(gestionCommande.listelivraison[i].date, mesCommandes.mesLivraison[i].date);

              if(mesCommandes.mesLivraison[i].date[0] != '\0'){
                gestionCommande.listelivraison[i].destination = mesCommandes.mesLivraison[i].destination;
                strcpy(gestionCommande.listelivraison[i].horaire, mesCommandes.mesLivraison[i].horaire);
                for(j=0;j<3;j++){
                  gestionCommande.listelivraison[i].maCommande.caddieCommande.mesArticles[j] = mesCommandes.mesLivraison[i].maCommande.caddieCommande.mesArticles[j];
                }
                gestionCommande.listelivraison[i].maCommande.compteClient = mesCommandes.mesLivraison[i].destination;
                gestionCommande.listelivraison[i].maCommande.monPayement = mesCommandes.mesLivraison[i].maCommande.monPayement;
                gestionCommande.listelivraison[i].note = mesCommandes.mesLivraison[i].note;
              }
            }
        malivraison.note = -1;
        gestionCommande.livraison = malivraison;

        result_6 = commandepayer_1(&gestionCommande, clnt);
      	if (result_6 == (void *) NULL) {
      		clnt_perror (clnt, "call failed");
      	}

        for(i =0;i<3;i++){
          if(result_6->mesLivraison[i].date != '\0'){
            mesCommandes.mesLivraison[i] = result_6->mesLivraison[i];
          }
          moncompteCo.monCaddie = moncompte.monCaddie;
        }
        break;
      case 5:
        total = 0;
        printf("\n");
        printf("\033[1;32m");
        printf("Mes Commandes : \n");
        printf("\033[0;0m");
        for(i=0; i<3; i++){
          if(mesCommandes.mesLivraison[i].date[0] != '\0'){
            j = 0;
            printf("\n");
            printf("\033[1;36m");
            printf("Commande [%d] :\n", i+1);
            printf("\033[0;0m");
            for(j=0; j<3; j++){
            printf("Produit [%d] : %s\n", j+1, mesCommandes.mesLivraison[i].maCommande.caddieCommande.mesArticles[j].nom);
            total += mesCommandes.mesLivraison[i].maCommande.caddieCommande.mesArticles[j].prix;
            }
            printf("Date : %s, %s\n", mesCommandes.mesLivraison[i].date, mesCommandes.mesLivraison[i].horaire);
            printf("\033[1;33m");
            printf("Prix : %2.2f €\n", total);
            printf("\033[0;0m");

          } else if(i==0){
            printf("\033[1;33m");
            printf("\nAucune commande !\n");
            printf("\033[0;0m");
            break;

          }
        }
        break;
      case 0:
        printf("\033[1;32m");
        mesCommandes = Commandesreset;
        printf("Merci d'avoir utilisé Panier Bio, ciao !\n");
        printf("\033[0;0m");
        break;

      default:
        printf("\033[1;33m");
        printf("ATTENTION : Mauvais code\n");
        printf("\033[0;0m");
        break;
    }
  }
}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	marche_prog_1 (host);
exit (0);
}
